name: Execute Job1
on:
  workflow_dispatch:
    inputs:
      input_data:
        description: 'Input data for Job1'
        required: true

jobs:
  run-job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: chmod +x job1.sh && ./Workflow/job1.sh "${{ inputs.input_data }}" > output.txt
      - uses: actions/upload-artifact@v4
        with:
          name: job1-output
          path: output.txt