name: Execute Job1
on:
  workflow_dispatch:
    inputs:
      input_data:
        description: 'Input data for Job1'
        required: true

permissions:
  contents: write
  actions: write
  checks: read

jobs:
  run-job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Run Job1 Script
        run: |
          # Use lowercase 'workflow' to match directory name
          cd workflow
          chmod +x job1.sh
          ./job1.sh "${{ inputs.input_data }}" > output.txt
          
      - name: Upload Output
        uses: actions/upload-artifact@v4
        with:
          name: job1-output
          path: workflow/output.txt  # Corrected to lowercase