name: Execute Job2
on:
  workflow_dispatch:
    inputs:
      job1_output:
        description: 'Output from Job1'
        required: true

permissions:
  contents: read
  actions: read

jobs:
  run-job2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Run Job2 Script
        run: |
          # Navigate to the Workflow directory
          cd Workflow
          chmod +x job2.sh
          ./job2.sh "${{ inputs.job1_output }}"